In [1]:
test = "Hello World" 
print(test)


Hello World


In [3]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
# Create an array with 3 integers, starting from the default integer 0. 
b = np.arange(5)
print(b)

[0 1 2 3 4]


In [5]:
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [7]:
line_spaced_arr = np.linspace(0, 100, 5)
print(line_spaced_arr)

[  0.  25.  50.  75. 100.]


In [8]:
line_spaced_arr = np.linspace(0, 100, 5, dtype= int)
print(line_spaced_arr)

[  0  25  50  75 100]


In [9]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [10]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [11]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML!']
<U23


In [12]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [13]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [14]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [15]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.82832011 0.79132457 0.36350986]


In [16]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [18]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [19]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [20]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size


6

In [21]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [22]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

In [23]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [26]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])
# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

8


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [28]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [29]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [30]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)


[[1 1 3 3]
 [2 2 4 4]]
