In [1]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np

In [4]:
matA = np.array (
    [ [4, 9, 9],
      [9, 1, 6],
      [9, 2, 3]
    ]
)
print(matA)

[[4 9 9]
 [9 1 6]
 [9 2 3]]


In [5]:
matB = np.array(
    [
        [2, 2],
        [5, 7],
        [4, 4]
    ]
)
print(matB)

[[2 2]
 [5 7]
 [4 4]]


In [6]:
np.matmul(matA, matB)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [7]:
matA @ matB

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [10]:
try:
    matA @ matB
except ValueError as er:
    print(er)

In [12]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

print("Shape of vaector x:", x.shape)
print("Shape fo vector y:", y.shape)
print("Num of Dimension of vector c:", x.ndim)


Shape of vaector x: (3,)
Shape fo vector y: (3,)
Num of Dimension of vector c: 1


In [13]:
print("Shape of vecotr X, reshaped to a matrix", x.reshape((3,1)).shape)
print("Number oif dimenstion of vector X, reshaped to a matric", x.reshape((3,1)).ndim)

Shape of vecotr X, reshaped to a matrix (3, 1)
Number oif dimenstion of vector X, reshaped to a matric 2


In [14]:
np.matmul(x,y)

np.int64(3)

In [15]:
np.dot(matA, matB)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])