In [2]:
import numpy as np
np.version.version

'1.21.1'

In [7]:
A = np.array([
    [4, -3, 1],
    [2, 1, 3],
    [-1, 2, -5]
],dtype=np.dtype(float))

b = np.array([10, 0, 17], dtype=np.dtype(float))
print("Matrix A:")
print(A)
print("\n Array b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

 Array b:
[10.  0. 17.]


In [8]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(b)}")

Shape of A: (3, 3)
Shape of B: (3,)


In [9]:
det = np.linalg.det(A)
print(f"Determinant of matrix A: {det:.2f}")

Determinant of matrix A: -60.00


In [10]:
print(np.linalg.solve(A, b))

[ 4.66666667  1.66666667 -3.66666667]
